### ISSUE TITLE
openbooks.princeton.edu is available to the world

### ISSUE THREAD

**Issue by bess** [pulibrary/openbooks#2]
- [ ] *AFTER* openbooks.princeton.edu is ready to go, make it available to the world

**Comment by carolyncole** [comment]
This was set up with deny to the world originally.  I'm unsure what the ticket is asking for: https://github.com/pulibrary/princeton_ansible/commit/05fd1534ade8b5e5883f2697bf22f37e22d1df5a#diff-d0222c7beedb8cf4c7ce1ec449f42d25abd70cfc1b9c0105057b17513560943aR42-R45
I was denied when I was not on VPN, and have access when on VPN
