### ISSUE TITLE
Set up openbooks monitoring 

### ISSUE THREAD

**Issue by bess** [pulibrary/openbooks#3]
**ACCEPTANCE CRITERIA**
- [ ] (Preferred) Set up Sensu monitoring of openbooks staging and production
OR
- [ ] If sensu isn't ready for this, set up Honeybadger monitoring

In both cases:
- [ ] Identify with the team who should get the alerts (Bess, Yuan, plus who?) 
- [ ] Document whatever we set up in the DRDS handbook

**Comment by jrgriffiniii** [comment]
Honeybadger monitoring is going to be needed until Sensu is available for another (separate) issue.
